# Generated by Django 4.1.4 on 2022-12-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enonce', models.TextField()),
                ('reponse', models.TextField()),
                ('repondu', models.BooleanField(default=False)),
                ('theme', models.CharField(choices=[('Art et littérature', 'Art'), ('Divertissement', 'Divertissement'), ('Géographie', 'Geographie'), ('Histoire', 'Histoire'), ('Sport', 'Sport'), ('Loisirs', 'Loisirs'), ('Sciences', 'Sciences')], default='Art et littérature', max_length=50)),
            ],
        ),
    ]
